import assert from 'node:assert/strict';
import fs from 'node:fs';
const renderer = fs.readFileSync(new URL('../src/render/threeRenderer.js', import.meta.url), 'utf8');
const factory = fs.readFileSync(new URL('../src/render/celestialFactory.js', import.meta.url), 'utf8');
assert.match(renderer, /new THREE\.PointLight\(0xffffff,\s*5\.5,\s*0,\s*0\)/, 'stellar renderer light must be exposure-normalized with no render-space attenuation');
assert.match(renderer, /sunLight\.color\.setHex\(body\.color/, 'stellar light should inherit generated star color');
assert.match(renderer, /new THREE\.AmbientLight\(0x263149,\s*0\.055\)/, 'ambient light should remain intentionally low');
assert.match(factory, /emissiveIntensity:\s*0\.13/, 'body material should have a small color-preserving exposure floor');
assert.match(factory, /opacity:\s*0\.10/, 'body exposure shell should guarantee readable seeded color on WebGPU/iOS');
console.log('renderLighting.test: ok');
